import { ElementData } from '../types';

export const MAX_PROTONS_DEFINED = 50; // Updated from 49 to 50
export const MAX_PARTICLES_CONTROL = 75; // Max value for particle controls

export const ELEMENTS_DATA: ElementData[] = [
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', atomicMass: 1.008, electronConfigurationShells: "1", fullElectronConfiguration: "1s¹" },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', atomicMass: 4.0026, electronConfigurationShells: "2", fullElectronConfiguration: "1s²" },
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', atomicMass: 6.94, electronConfigurationShells: "2, 1", fullElectronConfiguration: "1s² 2s¹" },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', atomicMass: 9.0122, electronConfigurationShells: "2, 2", fullElectronConfiguration: "1s² 2s²" },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', atomicMass: 10.81, electronConfigurationShells: "2, 3", fullElectronConfiguration: "1s² 2s² 2p¹" },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', atomicMass: 12.011, electronConfigurationShells: "2, 4", fullElectronConfiguration: "1s² 2s² 2p²" },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', atomicMass: 14.007, electronConfigurationShells: "2, 5", fullElectronConfiguration: "1s² 2s² 2p³" },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', atomicMass: 15.999, electronConfigurationShells: "2, 6", fullElectronConfiguration: "1s² 2s² 2p⁴" },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', atomicMass: 18.998, electronConfigurationShells: "2, 7", fullElectronConfiguration: "1s² 2s² 2p⁵" },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', atomicMass: 20.180, electronConfigurationShells: "2, 8", fullElectronConfiguration: "1s² 2s² 2p⁶" },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', atomicMass: 22.990, electronConfigurationShells: "2, 8, 1", fullElectronConfiguration: "[Ne] 3s¹" },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', atomicMass: 24.305, electronConfigurationShells: "2, 8, 2", fullElectronConfiguration: "[Ne] 3s²" },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminium', atomicMass: 26.982, electronConfigurationShells: "2, 8, 3", fullElectronConfiguration: "[Ne] 3s² 3p¹" },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', atomicMass: 28.085, electronConfigurationShells: "2, 8, 4", fullElectronConfiguration: "[Ne] 3s² 3p²" },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', atomicMass: 30.974, electronConfigurationShells: "2, 8, 5", fullElectronConfiguration: "[Ne] 3s² 3p³" },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', atomicMass: 32.06, electronConfigurationShells: "2, 8, 6", fullElectronConfiguration: "[Ne] 3s² 3p⁴" },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', atomicMass: 35.45, electronConfigurationShells: "2, 8, 7", fullElectronConfiguration: "[Ne] 3s² 3p⁵" },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', atomicMass: 39.948, electronConfigurationShells: "2, 8, 8", fullElectronConfiguration: "[Ne] 3s² 3p⁶" },
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', atomicMass: 39.098, electronConfigurationShells: "2, 8, 8, 1", fullElectronConfiguration: "[Ar] 4s¹" },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', atomicMass: 40.078, electronConfigurationShells: "2, 8, 8, 2", fullElectronConfiguration: "[Ar] 4s²" },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', atomicMass: 44.956, electronConfigurationShells: "2, 8, 9, 2", fullElectronConfiguration: "[Ar] 3d¹ 4s²" },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', atomicMass: 47.867, electronConfigurationShells: "2, 8, 10, 2", fullElectronConfiguration: "[Ar] 3d² 4s²" },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', atomicMass: 50.942, electronConfigurationShells: "2, 8, 11, 2", fullElectronConfiguration: "[Ar] 3d³ 4s²" },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', atomicMass: 51.996, electronConfigurationShells: "2, 8, 13, 1", fullElectronConfiguration: "[Ar] 3d⁵ 4s¹" },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', atomicMass: 54.938, electronConfigurationShells: "2, 8, 13, 2", fullElectronConfiguration: "[Ar] 3d⁵ 4s²" },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', atomicMass: 55.845, electronConfigurationShells: "2, 8, 14, 2", fullElectronConfiguration: "[Ar] 3d⁶ 4s²" },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', atomicMass: 58.933, electronConfigurationShells: "2, 8, 15, 2", fullElectronConfiguration: "[Ar] 3d⁷ 4s²" },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', atomicMass: 58.693, electronConfigurationShells: "2, 8, 16, 2", fullElectronConfiguration: "[Ar] 3d⁸ 4s²" },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', atomicMass: 63.546, electronConfigurationShells: "2, 8, 18, 1", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s¹" },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', atomicMass: 65.38, electronConfigurationShells: "2, 8, 18, 2", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s²" },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', atomicMass: 69.723, electronConfigurationShells: "2, 8, 18, 3", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹" },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', atomicMass: 72.630, electronConfigurationShells: "2, 8, 18, 4", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²" },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic', atomicMass: 74.922, electronConfigurationShells: "2, 8, 18, 5", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³" },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium', atomicMass: 78.971, electronConfigurationShells: "2, 8, 18, 6", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴" },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine', atomicMass: 79.904, electronConfigurationShells: "2, 8, 18, 7", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵" },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', atomicMass: 83.798, electronConfigurationShells: "2, 8, 18, 8", fullElectronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶" },
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', atomicMass: 85.468, electronConfigurationShells: "2, 8, 18, 8, 1", fullElectronConfiguration: "[Kr] 5s¹" },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', atomicMass: 87.62, electronConfigurationShells: "2, 8, 18, 8, 2", fullElectronConfiguration: "[Kr] 5s²" },
  { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', atomicMass: 88.906, electronConfigurationShells: "2, 8, 18, 9, 2", fullElectronConfiguration: "[Kr] 4d¹ 5s²" },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', atomicMass: 91.224, electronConfigurationShells: "2, 8, 18, 10, 2", fullElectronConfiguration: "[Kr] 4d² 5s²" },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', atomicMass: 92.906, electronConfigurationShells: "2, 8, 18, 12, 1", fullElectronConfiguration: "[Kr] 4d⁴ 5s¹" },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', atomicMass: 95.96, electronConfigurationShells: "2, 8, 18, 13, 1", fullElectronConfiguration: "[Kr] 4d⁵ 5s¹" },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', atomicMass: 98, electronConfigurationShells: "2, 8, 18, 13, 2", fullElectronConfiguration: "[Kr] 4d⁵ 5s²" }, // (Approx. mass for most stable isotope)
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', atomicMass: 101.07, electronConfigurationShells: "2, 8, 18, 15, 1", fullElectronConfiguration: "[Kr] 4d⁷ 5s¹" },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', atomicMass: 102.91, electronConfigurationShells: "2, 8, 18, 16, 1", fullElectronConfiguration: "[Kr] 4d⁸ 5s¹" },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', atomicMass: 106.42, electronConfigurationShells: "2, 8, 18, 18, 0", fullElectronConfiguration: "[Kr] 4d¹⁰" },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver', atomicMass: 107.87, electronConfigurationShells: "2, 8, 18, 18, 1", fullElectronConfiguration: "[Kr] 4d¹⁰ 5s¹" },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', atomicMass: 112.41, electronConfigurationShells: "2, 8, 18, 18, 2", fullElectronConfiguration: "[Kr] 4d¹⁰ 5s²" },
  { atomicNumber: 49, symbol: 'In', name: 'Indium', atomicMass: 114.82, electronConfigurationShells: "2, 8, 18, 18, 3", fullElectronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹" },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin', atomicMass: 118.71, electronConfigurationShells: "2, 8, 18, 18, 4", fullElectronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²" },
];
